# Generated by Django 2.2 on 2021-02-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comlete',
            new_name='complete',
        ),
    ]
